# https://docs.netlify.com/configure-builds/file-based-configuration/
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.new-face.environment]
  NODE_ENV = "staging"

[context.branch-deploy]
  NODE_ENV = "staging"